# SECRETS (MUST BE STORED SOMEWHERE ELSE OR AT ENVIRONMENT LEVEL)
_APP_SECRET_KEY = "networker-app-20190805"
_EMAIL_SERVER_SECRET_USERNAME = "networkeremailserver@gmail.com"
_EMAIL_SERVER_SECRET_APP_PASSWORD = "ikbfdabbziutojmg"
_EMAIL_SERVER_SECRET_PLATFORM = "smtp.gmail.com"
_EMAIL_SERVER_SECRET_PLATFORM_NUMBER = 587